version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: staylinker-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: staylinker
      POSTGRES_PASSWORD: staylinker
      POSTGRES_DB: staylinker
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
